services:
  # Первый сервис: FastCGI-приложение
  fastcgi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_server
    networks:
      - app_network

  # Второй сервис: Nginx для проксирования
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - fastcgi-app
    networks:
      - app_network
    ports:
      - "80:8080" # Мапим 8080 порт контейнера на 80 порт локальной машины
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf

networks:
  app_network:
    driver: bridge

